### ISSUE TITLE
[proposal] choose the target controller for actions based on the model instead of current controller

### ISSUE THREAD

**Issue by drewnichols** [ember-admin/ember-cli-admin#347]
The goal behind this change is to allow for 2 models with action buttons to be displayed under a single route. Currently when an action button (edit, show, etc...) is clicked the target controller the action is sent to is chosen based on the current route's controller. This proposed change would lead to selecting the target controller from the model name (which by convention i believe always matches the controller name) instead. 

This will allow us to display multiple models under a single route (which we can currently do) and support actions on each models.

**Comment by OpakAlex** [comment]
@drewnichols can we close this issue?

**Comment by drewnichols** [comment]
Yep

—
