### ISSUE TITLE
Touch support for TreeViewController?

### ISSUE THREAD

**Issue by zypo** [ember-admin/ember-cli-admin#365]
If it shouldn't just be an issue with the iOS Simulator, will there be touch support for the amazing TreeViewController?

I just stumbled over Ember CLI Admin, and I think the TreeViewController is the first serious Ember implementation of a tree view, with lots of potential.

Currently we implemented a tree using [jsTree](http://www.jstree.com), which has loads of features and we got it connected quite well with Ember. Also drag and drop somehow works on touch devices but is quite cumbersome.

**Comment by OpakAlex** [comment]
Hello!
We don't implement  touch support in ember-cli-admin. We can do it in feature, or you are wellcome)

**Comment by zypo** [comment]
Thanks, sure, if we should switch to it, we should be able to add touch support.

**Comment by OpakAlex** [comment]
if you need some questions or help, you can ping me.

**Comment by OpakAlex** [comment]
check new version 0.4.4
