### ISSUE TITLE
pod support

### ISSUE THREAD

**Issue by Globegitter** [ember-admin/ember-cli-admin#366]
It would be really great if the generators would support ember-cli's pod functionality: http://www.ember-cli.com/#pod-structure

**Comment by OpakAlex** [comment]
Hello!
We will look in this! Thanks!

**Comment by OpakAlex** [comment]
@Globegitter  check 0.4.4 version.

**Comment by OpakAlex** [comment]
@Globegitter check it from master.

**Comment by Globegitter** [comment]
Thank you @OpakAlex will try asap
