### ISSUE TITLE
ember g table-view-resource my-resources breaks router.js

### ISSUE THREAD

**Issue by Globegitter** [ember-admin/ember-cli-admin#376]
I just tried to install ember-cli-admin again and when running `ember g table-view-resource my-resources user` my `app/router.js` becomes `undefined` all of the sudden. As in everything in the file-content is overwritten by `undefined`. This is a blank ember-cli 0.2.1 app.

**Comment by OpakAlex** [comment]
hi! we will check it. thanks

**Comment by OpakAlex** [comment]
@Globegitter can you check it now?

**Comment by Globegitter** [comment]
@OpakAlex Sorry haven't been on that project for a while - will try to test asap and get back if there are still any issues. Thanks for looking into it!
