### ISSUE TITLE
Ideas from dockyard/ember-admin

### ISSUE THREAD

**Issue by Globegitter** [ember-admin/ember-cli-admin#378]
I love the idea of this plugin, how it looks and what features it has. But it seems to me that https://github.com/dockyard/ember-admin is much less intrusive into the app and therefore also quite simpler to set up.

The most basic set up are two easy steps:

`npm i ember-admin --save-dev` (or `npm i dockyard/ember-admin` ot get the latest)
followed by adding two lines to your `app/router.js`:
```js
import adminRouter from 'ember-admin/router';

Router.map(function() {
  adminRouter(this);
});
```

Now I have a quite simple admin ui that automatically picks up al my models. Didn't have to add or generate anything else. Then you can modify the settings to select which models to display and which not to display. I wonder if you have seen that addon before and if any ideas from it can be taken to improve this addon?

These are just my two cents after having used both and having tried to remove both again.

**Comment by OpakAlex** [comment]
Yes, it's simple, we can not works without controllers, because we have some extra features. If you need something poor use dockyard solution. If you need something complex use ember-cli-admin.

**Comment by tolgaek** [comment]
@OpakAlex I think you meant to say 'if you need something simple'
