### ISSUE TITLE
Material-design

### ISSUE THREAD

**Issue by Rastopyr** [ember-admin/ember-cli-admin#386]
May be add support of [ember-papaer](https://github.com/miguelcobain/ember-paper)?

Remarkup or multi-theme?

**Comment by OpakAlex** [comment]
multi-theme is good idea.
But it's some works :) You can try.

**Comment by Rastopyr** [comment]
okay :)
where i can find backend for testing?

**Comment by OpakAlex** [comment]
in https://github.com/ember-admin/ember-cli-admin/blob/master/server/mocks/app.js

But you can use mirage if you want.

**Comment by Rastopyr** [comment]
exactly! thanks

**Comment by OpakAlex** [comment]
@Rastopyr any news?)

**Comment by Rastopyr** [comment]
Nope :( i can't find time for this feature. You can close this issue, and if i will find opportunity, i opened issue again. Okay?
