### ISSUE TITLE
I have app/styles/app.scss, but I still get the error "app/styles/app.[scss/sass does not exist]"

### ISSUE THREAD

**Issue by mojied** [ember-admin/ember-cli-admin#391]
Hi,
My code: https://github.com/onecoinim/ember-cli-cms 

I have updated the ember-cli to v0.2.5 which is the same as ember-cli-admin.

Who can help me?
Thanks.

**Comment by OpakAlex** [comment]
hi man!
Are you sure this problem with admin? Without admin it works?

**Comment by mojied** [comment]
@OpakAlex hi, I find that "broccoli-sass" of the ember-cli-admin conflicts with the default addon of ember-cli-sass in the ember app. Why not use the ember-cli-sass?

**Comment by OpakAlex** [comment]
yes, maybe it's good idea use `ember-cli-sass`. Can you test and make PR ?

**Comment by mojied** [comment]
I'm afraid I have no enough time to do it recently. I'll try it.
