### ISSUE TITLE
Generate admin-app with ember cli 1.13.1 fails

### ISSUE THREAD

**Issue by harianus** [ember-admin/ember-cli-admin#411]
When running this command

```
$ ember g admin-app "Admin MGMco"
```

It gives me this error

```
version: 1.13.1
installing admin-app
Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at /development/admin/node_modules/ember-cli-admin/lib/proccess-text-content.js:27:45
```

It fails on this line [lib/proccess-text-content.js#L25](https://github.com/ember-admin/ember-cli-admin/blob/master/lib/proccess-text-content.js#L25)

**Comment by OpakAlex** [comment]
@igorrKurr can you look and help?
@harianus which version ember-cli are you using?

**Comment by harianus** [comment]
@OpakAlex TSIA ;-)

```
$ ember -v
version: 1.13.1
node: 0.12.2
npm: 2.12.1
```

**Comment by igorrKurr** [comment]
@harianus thanks for noticing this.

I'm gonna to to upgrade all generators soon, hope I'll have time for this on this weekend.

**Comment by harianus** [comment]
Nice, I will begin next week to use this admin tool very heavily. So I hope it is compatible soon with `ember cli 1.13.1`.

Will it be usable with the new ember versions as well next week?

**Comment by OpakAlex** [comment]
@harianus yes, we always up to date :)

**Comment by harianus** [comment]
@OpakAlex Ok, good to know!

Expect some bug reports and pull requests in the next weeks.

**Comment by harianus** [comment]
Nice work, thanks.
