### ISSUE TITLE
Missing dependency broccoli-funnel

### ISSUE THREAD

**Issue by Chrissvo** [ember-admin/ember-cli-admin#432]
When running `ember install ember-cli-admin` on a new ember app I get this error: `Cannot find module 'broccoli-funnel`.

Running `npm install broccoli-funnel` fixes the problem, just thought to let u guys know

**Comment by OpakAlex** [comment]
thanks! We will look :)

**Comment by OpakAlex** [comment]
@igorrKurr can you look?

**Comment by igorrKurr** [comment]
fixed in https://github.com/ember-admin/ember-cli-admin/commit/e9b4471648498f61812020cd8b1b7d7b51f543c0

**Comment by igorrKurr** [comment]
i'm closing it, please feel free to reopen if something gone wrong again with it.
