### ISSUE TITLE
Slugs in the urls instead of ids

### ISSUE THREAD

**Issue by harianus** [ember-admin/ember-cli-admin#434]
This tool is awesome, thanks for making it open source!

For the urls we have now the following structure

```
/projects/55ba164523d64eae5ab4de78/show
```

We want to show the slug (a project name which is url-safe) of a project in the url like this

```
/projects/project_slug/show
```

How could this be accomplished?

cc @chrissvo

**Comment by OpakAlex** [comment]
@harianus hi man.
Good point, for quick fix you can use slug as id. in serializer, we use primary key for url i think.

**Comment by harianus** [comment]
That works, but then there should be some deserialisation because the api only works with id's. Do you know how to do that?

**Comment by OpakAlex** [comment]
hm...it you look into this: 
https://github.com/ember-admin/ember-cli-admin/blob/master/addon/mixins/controllers/base-actions.js#L108

Can you remove before hook from serializer, and try override this method into your controller?

**Comment by harianus** [comment]
Ok, this is some low priority on our planning, so will close this now
