### ISSUE TITLE
Is it possible to overwrite components?

### ISSUE THREAD

**Issue by Chrissvo** [ember-admin/ember-cli-admin#436]
More a question than an issue.

I noticed that it is possible to overwrite templates like `show.hbs`, but I can't seem to overwrite components like `admin-td-element.hbs`.

Is that expected behavior? Any known workaround?

cc: @harianus

**Comment by OpakAlex** [comment]
you can create your component and extend it from exist.

**Comment by Chrissvo** [comment]
I'm not entirely sure where to override or extend on it. Tried the 3 locations highlighted below without success.

![screen shot 2015-08-19 at 13 20 00](https://cloud.githubusercontent.com/assets/2834982/9354978/108c9422-4675-11e5-9087-e86f4a968408.png)

**Comment by igorrKurr** [comment]
To extend component you can do 
```javascript
import targetComponent from 'ember-cli-admin/components/componentName'
import myLayout from 'myLayoutLocation'

export default targetComponent.extend({
  layout: layout
});
```

**Comment by Chrissvo** [comment]
Awesome, thanks we got it working!

Minor detail:
```js
export default targetComponent.extend({
  layout: myLayout
});
```
