### ISSUE TITLE
Use a different default breadcrumb

### ISSUE THREAD

**Issue by Chrissvo** [ember-admin/ember-cli-admin#437]
Can I set `home` as the default breadcrumb instead of `dashboard`?

Current structure:
![image](https://cloud.githubusercontent.com/assets/2834982/9360057/5adeaa8c-4694-11e5-82e3-9af02ce5fd54.png)

I'd like to structure it like this:
`home` > `projects` > `:id`
`home` > `dashboard`

**Comment by Chrissvo** [comment]
Solved by overriding the breadcrumbs template. Kind of dirty, but I don't think I can override the `_dashboard` function in `logics/breadcrumb.js`

```js
<ul class="breadcrumb">
  <li class="first">{{admin-letter-case content="Home"}}</li>
  {{#each content as |breadcrumb|}}
    {{#unless (is-equal breadcrumb.class "first")}}
      {{#if breadcrumb.active}}
        <li class="{{breadcrumb.class}}">{{admin-letter-case content=breadcrumb.name caseType=caseType}}</li>
      {{else}}
        <li class="{{breadcrumb.class}}">
          {{#link-to breadcrumb.url}}
            {{admin-letter-case content=breadcrumb.name caseType=caseType}}
          {{/link-to}}
        </li>
      {{/if}}
    {{/unless}}
  {{/each}}
</ul>
```

**Comment by OpakAlex** [comment]
@Chrissvo maybe better make in config option?

**Comment by OpakAlex** [comment]
and use from config. or make in controller some property?

**Comment by OpakAlex** [comment]
https://github.com/ember-admin/ember-cli-admin/blob/master/app/controllers/navigation.js Look into this. Why you don't want add property here?
