### ISSUE TITLE
'Method PATCH is not allowed by Access-Control-Allow-Methods' error

### ISSUE THREAD

**Issue by ugoa** [ember-admin/ember-cli-admin#438]
I am a newbie with `Ember.js` and `ember-cli-admin`, so I have a `/accounts` to get a accounts collection and it's been working. But when I tried to update a `account`, the browser console shown me the error:

`Method PATCH is not allowed by Access-Control-Allow-Methods`

and my Rails backend server didn't show any logs for this action. I had read somewhere said I need to set `Access-Control-Allow-Methods` to `POST, GET, OPTIONS, DELETE, PUT`

but how and at where? Is this a `ember.js` issue, `ember-cli-admin` issue or backend server setting issue?

Really appreciate it if anyone can help! Thanks in advance.

**Comment by igorrKurr** [comment]
Hi!
If you're using rails you have two options:
a)
```ruby
#app/controllers/application.rb
class ApplicationController < ActionController::Base
  before_action :enable_cors_headers

  def cors_preflight_check
    enable_cors_headers
    render nothing: true, content_type: 'text/plain'
  end

  protected

  def enable_cors_headers
    if request.headers["HTTP_ORIGIN"]
      headers['Access-Control-Allow-Origin']       = '*'
      headers['Access-Control-Expose-Headers']     = 'ETag'
      headers['Access-Control-Allow-Methods']      = 'GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD'
      headers['Access-Control-Allow-Headers']      = 'x-requested-with, Content-Type, origin, authorization, accept, client-security-token'
    end
  end

end

#config/routes.rb
match '*all', to: 'application#cors_preflight_check', via: :options
```
b) use https://github.com/cyu/rack-cors gem

**Comment by igorrKurr** [comment]
I closed this. If you have more questions, feel free to reopen.

**Comment by ugoa** [comment]
Thank you @igorrKurr . It worked!
