### ISSUE TITLE
How to make links in table cells which will route to the corresponding belongsTo route?

### ISSUE THREAD

**Issue by harianus** [ember-admin/ember-cli-admin#439]
It would be awesome to generate some links in the table view. The links should go to the corresponding route of the belongsTo model.

How can this be accomplished?

**Comment by OpakAlex** [comment]
yes, it's interesting. Also i think about table dsl in controller. For generate table attributes. 
For now you i don't known how to. but if you look into component you can see how to shows title/name for belogsTo in table.

**Comment by OpakAlex** [comment]
@harianus any updates?

**Comment by Chrissvo** [comment]
A possible solution could be to add this as a property in a model. Eg: I used this to display an avatar in a table-cell (fileUploads are not yet supported by our backend):

```js
avatarImage: function() {
    const imageUri = this.get('avatar');
    if (imageUri) {
      return '<img class="avatar-image" src="' + imageUri + '" />';
    }
    return;
  }.property('avatar')
```

Then update `tableAttributes` to display `avatarImage` instead of `avatar`.

Not sure if this would work with `link-to` helpers

**Comment by OpakAlex** [comment]
this can not works. 
But you can extend table component and template.

**Comment by Chrissvo** [comment]
Solved it by extending the `admin-td-element` component:

```js
import targetComponent from 'ember-cli-admin/components/admin-td-element';
import myLayout from './template';

export default targetComponent.extend({
  layout: myLayout,

  record: function() {
    const record = this.get(this.path());
    if (!record || (!record['get'] || !record.get('id'))) {
      return;
    }
    const recordId = record.get('id');
    const recordRoute = record.content._internalModel.modelName.pluralize() + '.show';
    return {
      id: recordId,
      route: recordRoute
    };
  }.property()

});
```

And then in the template:
```hbs
{{#unless image}}
  {{#unless record}}
    {{{value}}}
  {{else}}
    {{#link-to record.route  record.id}}{{value}}{{/link-to}}
  {{/unless}}
{{/unless}}
```
