### ISSUE TITLE
BelongsTo fields are not editable in edit or new route

### ISSUE THREAD

**Issue by Chrissvo** [ember-admin/ember-cli-admin#441]
Say I have a `product` that belongs to a certain `project`.

The project shows up in the `show`-route, but there is no input field in the `edit` or `new`-route:

![image](https://cloud.githubusercontent.com/assets/2834982/9439900/5e23db42-4a6b-11e5-8faa-4dc2df5e6bb1.png)

**Comment by OpakAlex** [comment]
you can override form.hbs and put your logic for this.

**Comment by Chrissvo** [comment]
Thanks. I did an overwrite on form.hbs and on admin-input.js to allow editing my belongsTo relations in a dropdown,

**Comment by OpakAlex** [comment]
nice! 
@Chrissvo you can make PR for this. We include it to default form. What you think?

**Comment by Chrissvo** [comment]
Sure, sounds good, I'll submit a PR later this week
