### ISSUE TITLE
BelongsTo attempts wrong model in edit route

### ISSUE THREAD

**Issue by Chrissvo** [ember-admin/ember-cli-admin#442]
For example. I have a `sale-model` with both a `seller` and a `buyer` who's properties are defined in the `user`-model.

```js
  seller: DS.belongsTo('user', {
    async: true
  }),
  buyer: DS.belongsTo('user', {
    async: true
  }),
```

When trying the edit route I get these errors:
`Uncaught Error: No model was found for 'seller'`
`Uncaught Error: No model was found for 'buyer'`

Can I overwrite this behavior in the add-on?

**Comment by OpakAlex** [comment]
this means you don't have model. It's not addon problem.

**Comment by Chrissvo** [comment]
Yeah I do have a user model, it works fine to retrieve data and in the tableview and show-route. 

It errors when going to the edit-route as it tries the seller-model which doesn't exist.

**Comment by OpakAlex** [comment]
heh. it's ember data issue. Admin don't request this as models.

**Comment by Chrissvo** [comment]
hmm, okay, I'll investigate a bit further

**Comment by OpakAlex** [comment]
or upload your app and i can look.

**Comment by igorrKurr** [comment]
it seems you need to customize your serializer for this model like this http://emberjs.com/api/data/classes/DS.RESTSerializer.html#method_serializeBelongsTo

**Comment by Chrissvo** [comment]
Haha, I found the issue! It was caused by my own overwrite of `admin-input` component: https://github.com/ember-admin/ember-cli-admin/issues/441. I guess I'll do some more debugging before submitting that PR ;)
