### ISSUE TITLE
Nested routes?

### ISSUE THREAD

**Issue by Chrissvo** [ember-admin/ember-cli-admin#443]
Hi guys,

Is it somehow possible to add nested routes? For example I have a set of projects that have users that belong to them.

To get all my projects I go to `/projects`
To get all my users I go to `/users`

To get the users of a project I'd like to go to `/projects/:projectId/users`
To get the projects of a user I'd like to go to `/users/:userId/projects`

In a similar fashion as `/projects/:projectId/show`

I tried extending the MetaRoute class and editing the ember router, but no luck yet...

**Comment by OpakAlex** [comment]
It's good point :)
For this you need create own routes, not use meta route.
Then you need create route.js and override `model` function.

**Comment by OpakAlex** [comment]
Maybe it will be good add some params to meta route for auto create this routes. We need think about it. You can start with easy part.

**Comment by Chrissvo** [comment]
Okay cool, I'll give it a shot! Shall I close this issue?

**Comment by OpakAlex** [comment]
you can try, if all is good, you can close)

**Comment by Chrissvo** [comment]
I've set up my own routes in the router, looking like this:
```js
Router.map(function() {

  this.route('projects', {
    path: '/projects'
  });

  this.route('projects.show', {
    path: '/projects/:id/show'
  });

  this.route('projects.edit', {
    path: '/projects/:id/edit'
  });

  this.route('projects.new', {
    path: '/projects/new'
  });

  this.route('projects.content-elements', {
    path: '/projects/:id/users'
  });

});
```
Also I'm overwriting the model function in:
`app/routets/projects/users.js`

```js
import Ember from 'ember';
import ModelAdminRouteMixin from 'ember-cli-admin/mixins/routes/model';

export default Ember.Route.extend(ModelAdminRouteMixin, {

  model: function(options, transition) {
    // hello I'm an overwrite
    var projectId = options.id;
    // set options to empty to get rid of the project id
    options = {};
    this.action = undefined;
    this.page = undefined;
    this.perPage = undefined;
    // take the singularized 2nd part of targetName
    this.modelName = transition.targetName.split('.')[1].singularize();
    this.page = (options != null ? options.page : void 0) || 1;
    this.perPage = (options != null ? options.perPage : void 0) || 25;
    // request for this project only
    this.q = {
      project: projectId
    }
    this.sort = (options != null ? options.sort : void 0);
    this.orderAscending = (options != null ? options.orderAscending : void 0);
    //this._checkAction(options, transition.targetName);
    if (options.action) {
      //this._setAction(options.action);
    }
    if (!this.container.lookupFactory('model:' + this.modelName)) {
      if (this.modelName.match(/dashboard/) || this.modelName.match(/index/) || this.modelName.match(/application/)) {
        return;
      }
      return Ember.RSVP.reject('No model was found');
    }
    if (this.store.modelFor(this.modelName)) {
      return this._find_model(this.modelName, options);
    }
  },
_find_model: function(modelName, options) {
    if (options.action === "new") {
      return this.store.createRecord(modelName, {});
    }
    if (!options.id) {
      var findOptions = {
        page: this.page,
        perPage: this.perPage,
        orderAscending: this.orderAscending
      };
      if (!Ember.isEmpty(this.q)) {
        findOptions.q = this.q;
      }
      if (!Ember.isEmpty(this.sort)) {
        findOptions.sort = this.sort;
      }
      // changed to store.query
      return this.store.query(modelName, findOptions);
    }
    return this.store.find(modelName, options.id);
  },
});
```

- I've set options to an empty array to get rid of the project id
- I modified `this.modelName` to take the `users` part of the targetName
- I've set q to request for a specific project id
- I uncommented `_checkAction` and `_setAction` because these functions error (ember can't find them) and they are not really needed in this case
- I also used `store.query` in `_find_model` as the `pagination`-function would throw an error

Seems to work, it makes the correct request to the server, but... gives me a blank page, so I'm missing something somewhere... The tab title says `users-loading -list`. Any ideas?

**Comment by OpakAlex** [comment]
hi man.
correct, you need create route for projects.content-elements
folder projects/content-elements.js
Then write your model function.
then render template.
Admin only put CRUD actions....any custom routes you can create as ember routes.

**Comment by Chrissvo** [comment]
Got it, forgot to render the template!

There is a set of things that belongs to projects (users, content-elements, etc.). I'm trying to get them in a CRUD admin interface.

- `projects/:projectId/users` would render a table with users of that project
- `projects/:projectId/users/:userId/edit` would edit a particular user of that project

But maybe that's taking it a step to far ;)

**Comment by OpakAlex** [comment]
What is profit make this routes? Only for filters projects by user?

**Comment by Chrissvo** [comment]
Security, separating out information by project for specific admin-users. But thinking about it, this should be done at the API end, so I'm probably better off using a predefined filter

**Comment by Chrissvo** [comment]
Thanks for all the explanation, pretty cool to figure out how this works! Nice job on the add-on!

**Comment by Chrissvo** [comment]
Just to finish off this thread:

I overwrote the model function to read out my queryParams and add them to q. Associated buttons are added as a component to `projects/show.hbs`.

```js
// add query params to q
if (Object.keys(transition.queryParams).length > 0) {
  Object.keys(transition.queryParams).forEach(function(key) {
    if (!Ember.isEmpty(this.q)) {
      this.q.concat(encodeURI('&' + key + '[value]=' + transition.queryParams[key]));
    } else {
      this.q = encodeURI(key + '[value]=' + transition.queryParams[key]);
    }
  }.bind(this));
}
```

Thanks guys!

**Comment by OpakAlex** [comment]
yes. more easy way :)
