### ISSUE TITLE
Implementing date ranges as filters in sidebar?

### ISSUE THREAD

**Issue by Chrissvo** [ember-admin/ember-cli-admin#444]
Any experience with using date ranges as a filter?

Example: Filter on `createdAt` from/to a certain date

How should this work out in the queryParameters? Something like `q=createdAt[gte]=10-10-2015&createdAt[lte]=12-10-2015`?

**Comment by igorrKurr** [comment]
Hi!
You can example of using date filter here - https://github.com/ember-admin/ember-cli-admin/blob/master/tests/dummy/app/controllers/users.js#L16

**Comment by Chrissvo** [comment]
Cool, but how would this work if I have a from & to field?

` this.input('birthdateFrom', {type: 'date', placeholder: "Select birthdate from", format: "dd MM, yyyy"});`
` this.input('birthdateTo', {type: 'date', placeholder: "Select birthdate to", format: "dd MM, yyyy"});`

Can I define the `[value]` part of `q` to look like `[gte]`/`[lte]`?

**Comment by OpakAlex** [comment]
i think this part need to implement :)

**Comment by Chrissvo** [comment]
Haha, okay I'll do some research and post back if we have a solution ;)

**Comment by OpakAlex** [comment]
check Search DSL

**Comment by Chrissvo** [comment]
We got this working, but I'm not sure if it is useful as a pull request, because we did some heavy overriding to make the admin compliant with these API specs: http://mgmco.github.io/api-query-spec/

End result works like this:
- to avoid overwriting the same field, we use _'_to'_ and _'_from'_ as additions to the key
- the search function reads this out and updates the key.value to match API specs
- objects to query are stored in queryParams
- router is refreshed

```js
import ENV from 'admin/config/environment';
import SearchController from 'ember-cli-admin/mixins/controllers/search';

export default SearchController.reopen({

  actions: {
    search: function() {
      var query = this.get('searchForm').serialize();
      var queryParams = this.get('queryParams');
      for (var key in query) {
        if (query.hasOwnProperty(key)) {
          var keyValue = query[key].value;
          if (key.indexOf('_') > 0) {
            var predicate = key.split('_')[1];
            key = key.split('_')[0];
            if (predicate === 'to') {
              keyValue = query[key + '_from'].value + '...' + keyValue;
            }
          }
          if (query[key].predicat) {
            if (query[key].predicat !== '=') {
              keyValue = query[key].predicat + keyValue;
            }
          }
          // set search key as a property
          this.setProperties({
            [key]: keyValue
          });
          Ember.$.extend(this.get('target.router.state.queryParams'), this.getProperties(key));
        }
      }
      // add query to the queryParams
      queryParams = this.getProperties();
      this.setProperties({
        page: 1
      });
      Ember.$.extend(this.get('target.router.state.queryParams'), this.getProperties('page'));
      this.get('target.router').refresh();
    }
  }
});
```

Closing this issue, thanks for the advice!
