### ISSUE TITLE
Ability to disable the new button

### ISSUE THREAD

**Issue by harianus** [ember-admin/ember-cli-admin#447]
It would be nice to have the option to disable a new item in the controller of the corresponding model.

Just where the settings for `tableAttributes`, `formAttributes`, ... are located.

**Comment by OpakAlex** [comment]
it's breadcrumbs controller i think.

**Comment by OpakAlex** [comment]
Check please `allActions`

**Comment by igorrKurr** [comment]
seems like similar to #445
